name: chanel
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.9
  - pytorch=1.7.1
  - flask=1.1.2
  - pip=21.0.1
  - pip:
    - clip-by-openai==0.1.1.5
    - dall-e==0.1
    - tqdm==4.58.0